//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SAM.Domain.ValidationPocos
{
    public partial class ValidationRestriction
    {
        public ValidationRestriction()
        {
            this.Role = new HashSet<ValidationRole>();
        }
    
    	[Required]
        public int Id { get; set; }
    	[Required]
    	[MaxLength(50)]
        public string Name { get; set; }
    	[Required]
    	[MaxLength(75)]
        public string Parent { get; set; }
    	[MaxLength(75)]
        public string Child { get; set; }
    	[Required]
        public bool RestrictAllChildren { get; set; }
    
        public virtual ICollection<ValidationRole> Role { get; set; }
    }
}
